### ISSUE TITLE
Error: You can only torch.load from a file that is seekable.

### ISSUE THREAD

**Issue by cirobotta** [IdoSpringer/ERGO#1]
Hi,
I'm unable to use the script in any of its part. Unfortunately, with or without CUDA, everytime I try to use it, I always receive this error: 
'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable.
 
Could you please help me?
I'm on Windows 10 and Anaconda with py 3.7.1
Thanks

**Comment by IdoSpringer** [comment]
Better late than never-
I think you tried using the autoencoder model file and it was not loaded correctly.
Anyway, this is now fixed in our productive repository at https://github.com/louzounlab/ERGO.
